### PR TITLE
Promote JUnit Lambda campaign on JUnit website

### PR DESCRIPTION
**Pull request by marcphilipp**
This adds a teaser to the landing page along with a separate page that states the campaign rationale and vision, and links to a [Google form](https://docs.google.com/forms/d/19-VHMXLYk9Hh0a3S6rYOXozU5WMX01wF3Z-BVkMy5J0/viewform) that allows to register for notification when the campaign starts.

You can download a zipped build from my Dropbox:
https://www.dropbox.com/s/a6q4j1ilr0fq4kg/junit-4.13-SNAPSHOT-site.zip?dl=0

index-page

lambda-page

### CODE REVIEW

**Comment by marcphilipp** [comment]
@junit-team/junit-contributors Any objections to this pull request? I would like to merge it this weekend at the latest.

**Comment by marcphilipp** [comment]
@junit-team/junit-committers Any objections to this pull request? I would like to merge it this weekend at the latest.

**Comment by jlink** [comment]
Not from my side.

2015-03-19 9:41 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by dsaff** [comment]
I certainly am fine with this going as is.

If any changes happen, I don't feel like the current text makes clear what is meant by "decouple test execution and reporting from test definition and provisioning", since that has been an implicit goal of the framework all along, and an explicit goal from 4.0 on.

It may make sense to have at least three bullet points of use cases that are impossible or difficult on 4.12, and become possible/easier after this effort.

**Comment by kcooney** [comment]
Beautiful. Nicely done!

I agree with David about the bullets. Perhaps remove the first bullet, and split the second into multiple bullets ("replace the easy-to-misuse `ExpectedException` rule with clean and simple lambda-based assertions.", "use lambdas to cleanly define parameterized tests")

One non-lambda feature we were thinking is reducing the need for runners by providing reusable extension points for parameterized test, theories and test lifecycle. That might be done on the JUnit 5 branch, though.

**Comment by jlink** [comment]
Maybe we could clarify the first point to something like that:
"*Strongly decouple test execution and reporting from test definition and
provisioning by providing two separate APIs in separate packages*"
Adding a few explaining scenarios might clarify even more.

As for the Lambda features: We've been vague on purpose since we don't know
how many features will make it into JUnit Lambda.

The "reusable extension points for parameterized test, theories and test
lifecycle" is IMO
stuff for JUnit 5 because it will break existing code - unless we want to
support both the old ways and the new ones. My guess is, that JUnit 5 will
not be in scope for the campaign since 6 weeks are just well only 6 weeks
:-/

Johannes

2015-03-19 15:40 GMT+01:00 Kevin Cooney <notifications@github.com>:

**Comment by kcooney** [comment]
Still unclear as to what issues are being fixed by "Strongly decouple test execution and reporting from test definition and
provisioning". Is there a doc describing this? Things seem reasonably decoupled now

**Comment by jlink** [comment]
It's described the campaign vision:
https://docs.google.com/document/d/1L0XOf74nfuitIEGj39jNyRHAP3wYOdYHibmmAPlkiJI/edit#heading=h.gic3tbsbvmpd

2015-03-19 18:53 GMT+01:00 Kevin Cooney <notifications@github.com>:

**Comment by kcooney** [comment]
@jlink thanks for the link.

I think "to enable parallel and continuous test execution out of the box" would be a better thing to promote on the crowdfunding page rather than simplifying evolution of JUnit. Stated another way, if we only list a few things we hope to do, we should focus on the ones that would directly benefit average users of JUnit. That's not to say the others are important, but it's harder to get most users excited about them.

**Comment by kcooney** [comment]
Any update on updating the pull to improve the bulleted text?

**Comment by marcphilipp** [comment]
@kcooney We will work on it. Since the campaign has been postponed for a couple of months, I'm closing this pull request for now.

**Pull request closed without merging**
