### PR TITLE
Change method getFilteredChildren's visibility to protected

### PR DESCRIPTION
**Pull request by sduxzz**
Change method getFilteredChildren's visibility to protected, so this method can be called by subclasses

### CODE REVIEW

**Comment by kcooney** [comment]
Can you give a use case for why subclasses would need to call this?

**Comment by sduxzz** [comment]
hi, I would like to override childrenInvoker method, so I can redefine the process how children will be run. But, runChildren and getFilteredChildren method are all private, so I can't do that. Example code:
```java
public class SomeRunner<T> extends ParentRunner<T> {
      @Override
    protected Statement childrenInvoker(final RunNotifier notifier) {
        List<T> filteredChildren = new ArrayList<T>(getFilteredChildren()); // Cant't access getFilteredChildren()
        return new ChristStatement<T>(getTestClass(), filteredChildren, notifier, this, executor());
    }
}
 ```

**Comment by kcooney** [comment]
@sduxzz could you solve your problem by overriding `runChild()`? Can you give more details about what you are trying to do? Making private methods protected makes the class harder to maintain, so it's good to know what problem(s) you are trying to solve first.

**Comment by sduxzz** [comment]
@kcooney Thank you for your reply. I will try to use your advice to solve my problems.  : ) 
By the way, can junit support running test cases concurrently in future? In other words, can users use something to tell junit framework run these test cases sequently and  runother test cases concurrently  in future?

**Comment by sduxzz** [comment]
@kcooney Thank you for your reply. I will try to use your advice to solve my problems. : )

**Comment by kcooney** [comment]
@sduxzz did the advice help, or do we still need this pull request?

**Comment by sduxzz** [comment]
@kcooney  yes,  thank you for your advice,  and this pull request can be closed.

**Pull request closed without merging**
