### PR TITLE
Add missing @since Javadoc to createTest(FrameworkMethod)

### PR DESCRIPTION
**Pull request by kcooney**

### CODE REVIEW

**Comment by kcooney** [comment]
Note: to keep the commit history cleaner, I would prefer that this get merged with the 'hub' tool. If the other maintainers haven't setup hub, I would be happy to merge this myself once I get a LGTM.

**Comment by kcooney** [comment]
Hmm.. not sure how those unrelated changes to TemporaryFolder got there. I'll clean those up now.

**Comment by marcphilipp** [comment]
According to Travis this does not compile due to an error introduced in the previous commit. Please merge #1062 (using hub) first and rebase this pull request on the resulting master.

**Comment by kcooney** [comment]
Will fix this tonight

**Comment by kcooney** [comment]
Rebased. PTAL

**Comment by marcphilipp** [comment]
LGTM!

**Comment by marcphilipp** [comment]
@kcooney Are you going to merge this using hub yourself or do you need help?

**Comment by kcooney** [comment]
I will try to merge this weekend. Extremely busy during the week

**Comment by kcooney** [comment]
merged

**Pull request closed without merging**
