### PR TITLE
Remove deprecated JUnitSystem.exit() method

### PR DESCRIPTION
**Pull request by marcphilipp**
Do we need to wait two years to remove this?

### CODE REVIEW

**Comment by kcooney** [comment]
LGTM

@junit-team/junit-committers any objections?

BTW, I think having two maintainers agree to merge something is generally sufficient (so if one maintainer makes a pull, another can merge it). For removing APIs, however, I would prefer if we have at least three maintainers agree to merge.

**Comment by marcphilipp** [comment]
:+1: I agree to the 3/4 guideline. I had the same gut feeling.

**Comment by dsaff** [comment]
Looks good to me!

**Comment by stefanbirkner** [comment]
LGTM. And I agree to the 2/4 and 3/4 guidelines.

**Comment by marcphilipp** [comment]
This was deprecated in 4.12. According to our discussed deprecation policy we have to wait at least a year to remove it, haven't we?

**Comment by kcooney** [comment]
Yes, we should wait to remove it. Let's close this for now.

**Pull request closed without merging**
