### PR TITLE
Update TestFailure.java

### PR DESCRIPTION
**Pull request by SnailKnows**

### CODE REVIEW

**Comment by baev** [comment]
I guess this PR has no effect. `PrintWriter#close()` only close his writer (In this case it is `StringWriter`). From `StringWriter#close()` docs: 

*Closing a <tt>StringWriter</tt> has no effect. The methods in this class can be called after the stream has been closed without generating an <tt>IOException</tt>.*

**Comment by kcooney** [comment]
Agreed. In fact, flushing a `StreamWriter` has no effect, either

@SnailKnows did your IDE show a warning here?

**Comment by SnailKnows** [comment]
Thanks.I understand after reading the source of StringWriter.

**Comment by SnailKnows** [comment]
@kcooney  Not warning.

**Pull request closed without merging**
