### PR TITLE
Add assertThrows

### PR DESCRIPTION
**Pull request by rschmitt**
This is a rough cut (no Javadoc, public interfaces in Assert, questionable formatting, etc), but I want to first get consensus that these methods are worth adding. The goal here is to provide (in a backwards-compatible manner) a Lambda-based exception API as hinted at by #1106. (It's important to comprehend that lambdas are provided by the call site; there is no reason why a JDK5-based library cannot facilitate the use of lambda expressions, method references, and higher order functions in general.)

I have not implemented assertThrows in terms of Matchers, since the Hamcrest stuff appears to be on the way out (and rightly so).

### CODE REVIEW

**Comment by kcooney** [comment]
Thanks for starting the conversation.

Some of us were leaning towards having these methods return the exception that was thrown, so the user can use their favorite assertion framework (Truth, Hamcrest, Fest, etc) to make further assertions on the message, cause or custom attributes of the test

**Comment by rschmitt** [comment]
That's an interesting idea. I guess that would look something like:

```java
expectThrow(client::invoke); // throw anything
assertTrue(expectThrow(client::invoke) instanceof RuntimeException); // throw a specific type
assertEquals("message", expectThrow(client::invoke).getMessage()); // throw a specific message
```

This is clearly simpler. It also gets you out of having to copy the `Predicate<T>` interface (although you still want `ThrowingRunnable` for ergonomic reasons). I like it.

**Comment by kcooney** [comment]
We could also allow the caller to pass in the type of the expected exception:

    IllegalArguementException e = expectThrows(
        IllegalArguementException.class, client::invoke);
    assertThat(e.getMessage()).contains("boom");

**Comment by rschmitt** [comment]
Well, maybe. There's already a bit of a Cartesian explosion going on with all the convenience methods (message or no message, Callable/Runnable/ThrowingRunnable; adding an optional Class makes it twelve methods). Additionally, a separate assertion on the expected exception type seems to do a better job of separating the "act" part of the test from the "assert" part.

**Comment by kcooney** [comment]
@rschmitt why do we need to support Callable, Runnable and ThrowingRunnable? Why can't we just support ThrowingRunnable? Are the extra overloaded there for people that can't use JDK 8?

If we don't need to support Runnable or Callable, then we have four overloads: with and without a message, and with or without the expected exception type.

We would only have two overloads if we require the expected exception, which I think we should. Asserting that *any* exception is thrown should be rare.

While I do like splitting "act" vs "assert", any lambda based approach is doing both, because the method calls the lambda, and if there is no exception thrown by the lambda, the method should throw an `AssertionError`

**Comment by rschmitt** [comment]
@kcooney I'll need to review the details on this, but the basic idea is that Java does not reliably infer a void SAM type from a reference to a non-void method. Moving the type assertions out doesn't completely decouple execution from assertion, but it provides you the greatest degree of decoupling possible, given the fact that throwing exceptions is inextricably linked to execution flow.

**Comment by rschmitt** [comment]
It turns out you're right about `ThrowingRunnable`. If that is the only type offered, we can support all four cases without wrapping:

* void methods that don't throw
* non-void methods that don't throw
* void methods that throw
* non-void methods that don't throw

The result otherwise is either type errors related to checked exceptions or an ambiguous method call.

**Comment by rschmitt** [comment]
Oh, and the other possibility is `cannot convert void to java.lang.Object`. Java will discard a return value to make SAM type inference work out, but it won't make one up.

**Comment by rschmitt** [comment]
New proposal is at #1154

**Pull request closed without merging**
