### PR TITLE
refactory applying clean code

### PR DESCRIPTION
**Pull request by AlisonSouza**

### CODE REVIEW

**Comment by kcooney** [comment]
Why are you changing the code to set `boolean` fields to `Boolean` values (forcing am implicit auto-unbox)?

**Comment by AlisonSouza** [comment]
Both are unboxed, I believe Boolean.TRUE is more elegant than true,
it's as Bigdecimal, Example:

BigDecimal b1 = new BigDecimal(10);
BigDecimal b2 = BigDecimal.TEN;

Both are correct, but I think BigDecimal.TEN is more legible

What do you think about?


Sorry my english, I am from Brazil

**Comment by Tibor17** [comment]
`boolean b = Boolean.TRUE` b*l*s*t  
Setting unboxed object to primitive is 100 years before monkeys.

**Comment by kcooney** [comment]
`Boolean.TRUE` is a Boolean, not a boolean. I think I prefer the original code.

**Pull request closed without merging**
