### PR TITLE
Make exception message more descriptive

### PR DESCRIPTION
**Pull request by shadowfacts**

### CODE REVIEW

**Comment by marcphilipp** [comment]
I'm not a native speaker but I think "void method" is a set expression. 

@dsaff @kcooney What do you think?

**Comment by kcooney** [comment]
I think "Method foo() should have a return type of void" or "Method foo() should have a void return type" would both be fine. I am personaly not a fan of appending "'s" to the method name.

**Comment by dsaff** [comment]
Agreed that the space after the method name needs to go back in.  "Method foo() should return void" seems succinct and correct, as another option.

**Comment by dsaff** [comment]
Thanks for doing this.

**Comment by kcooney** [comment]
Squashed commits and merged. Thanks!

**Pull request closed without merging**
